/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from '@supabase/supabase-js';
import { profileSchema,organizationRoleSchema,organizationSchema,vehicleSchema,ownershipSchema,vehicleMakeSchema,vehicleModelSchema,serviceCategorySchema,serviceSchema,locationSchema,serviceRequestSchema,jobOfferSchema,assignmentSchema,publicMechanicSchema,publicShopSchema,publicServiceSchema,mechanicSearchResultSchema,shopSearchResultSchema,serviceSearchResultSchema } from '@cnmechanic/schemas';
import type { z } from 'zod';
import type { mechanicSearchInputSchema,shopSearchInputSchema,serviceSearchInputSchema } from '@cnmechanic/schemas';
import type { IdentityRepository } from '@cnmechanic/domain';
import type { WorkerConfig } from '@cnmechanic/config';
import type { Identity } from './auth';
import { AppError } from './errors';
export function identityRepository(identity:Identity):IdentityRepository{
 async function profile(displayName?:string){
  const query=displayName===undefined?identity.client.from('profiles').select('id,display_name,created_at').eq('id',identity.userId):identity.client.from('profiles').update({display_name:displayName}).eq('id',identity.userId).select('id,display_name,created_at');
  const {data,error}=await query.single();if(error || !data)throw new AppError('SERVICE_UNAVAILABLE',503,'Profile is unavailable.');
  return profileSchema.parse({id:data.id,displayName:data.display_name,createdAt:new Date(data.created_at as string).toISOString()});
 }
 return {getProfile:()=>profile(),updateProfile:profile};
}
export async function getOrganization(identity:Identity,id:string){
 const {data:members,error:memberError}=await identity.client.from('organization_memberships').select('role').eq('organization_id',id).eq('user_id',identity.userId).eq('active',true);
 if(memberError)throw new AppError('SERVICE_UNAVAILABLE',503,'Membership service is unavailable.');
 const roles=organizationRoleSchema.array().parse((members??[]).map(m=>m.role));
 if(!roles.length)throw new AppError('FORBIDDEN',403,'Organization access is not permitted.');
 const {data,error}=await identity.client.from('organizations').select('id,name').eq('id',id).single();
 if(error || !data)throw new AppError('FORBIDDEN',403,'Organization access is not permitted.');
 return organizationSchema.parse({...data,roles});
}
const iso=(value:string)=>new Date(value).toISOString();
function vehicle(row:any){const model=row.vehicle_models;return vehicleSchema.parse({id:row.id,model:{id:model.id,makeId:model.make_id,name:model.name,slug:model.slug,startYear:model.start_year,endYear:model.end_year},modelYear:row.model_year,trim:row.trim,engineDescription:row.engine_description,propulsionType:row.propulsion_type,drivetrain:row.drivetrain,transmissionType:row.transmission_type,mileage:row.mileage,status:row.status,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)});}
function unavailable(error:unknown){if(error)throw new AppError('SERVICE_UNAVAILABLE',503,'Core domain data is unavailable.');}
export async function listVehicles(identity:Identity){const {data,error}=await identity.client.from('vehicles').select('id,model_year,trim,engine_description,propulsion_type,drivetrain,transmission_type,mileage,status,created_at,updated_at,vehicle_models(id,make_id,name,slug,start_year,end_year)').order('created_at',{ascending:false});unavailable(error);return (data??[]).map(vehicle);}
export async function getVehicle(identity:Identity,id:string){const {data,error}=await identity.client.from('vehicles').select('id,model_year,trim,engine_description,propulsion_type,drivetrain,transmission_type,mileage,status,created_at,updated_at,vehicle_models(id,make_id,name,slug,start_year,end_year)').eq('id',id).maybeSingle();unavailable(error);if(!data)throw new AppError('NOT_FOUND',404,'Vehicle was not found.');return vehicle(data);}
export async function createVehicle(identity:Identity,input:any){const {data,error}=await identity.client.rpc('create_vehicle_with_owner',{p_model_id:input.modelId,p_model_year:input.modelYear,p_trim:input.trim??null,p_engine_description:input.engineDescription??null,p_propulsion_type:input.propulsionType,p_drivetrain:input.drivetrain??null,p_transmission_type:input.transmissionType??null,p_mileage:input.mileage??null,p_vin:input.vin??null});if(error||!data)throw new AppError('CONFLICT',409,'Vehicle could not be created.');return getVehicle(identity,data);}
export async function listOwnerships(identity:Identity,id:string){const {data,error}=await identity.client.from('vehicle_ownerships').select('id,vehicle_id,ownership_status,ownership_started_at,ownership_ended_at,source_type').eq('vehicle_id',id).order('ownership_started_at',{ascending:false});unavailable(error);return (data??[]).map((row:any)=>ownershipSchema.parse({id:row.id,vehicleId:row.vehicle_id,ownershipStatus:row.ownership_status,ownershipStartedAt:iso(row.ownership_started_at),ownershipEndedAt:row.ownership_ended_at?iso(row.ownership_ended_at):null,sourceType:row.source_type}));}
function publicClient(config:WorkerConfig){if(!config.SUPABASE_URL||!config.SUPABASE_PUBLISHABLE_KEY)throw new AppError('SERVICE_UNAVAILABLE',503,'Catalog is unavailable.');return createClient(config.SUPABASE_URL,config.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});}
export async function listVehicleMakes(config:WorkerConfig){const {data,error}=await publicClient(config).from('vehicle_makes').select('id,name,slug').order('name');unavailable(error);return (data??[]).map((x:any)=>vehicleMakeSchema.parse(x));}
export async function listVehicleModels(config:WorkerConfig){const {data,error}=await publicClient(config).from('vehicle_models').select('id,make_id,name,slug,start_year,end_year').order('name');unavailable(error);return (data??[]).map((x:any)=>vehicleModelSchema.parse({id:x.id,makeId:x.make_id,name:x.name,slug:x.slug,startYear:x.start_year,endYear:x.end_year}));}
export async function listCategories(config:WorkerConfig){const {data,error}=await publicClient(config).from('service_categories').select('id,name,slug,description').order('name');unavailable(error);return (data??[]).map((x:any)=>serviceCategorySchema.parse(x));}
export async function listServices(config:WorkerConfig){const {data,error}=await publicClient(config).from('services').select('id,category_id,name,slug,description').order('name');unavailable(error);return (data??[]).map((x:any)=>serviceSchema.parse({id:x.id,categoryId:x.category_id,name:x.name,slug:x.slug,description:x.description}));}
export async function listLocations(identity:Identity,organizationId:string){const {data,error}=await identity.client.from('locations').select('id,organization_id,name,slug,location_type,status,city,region,country_code,timezone').eq('organization_id',organizationId);unavailable(error);return (data??[]).map((x:any)=>locationSchema.parse({id:x.id,organizationId:x.organization_id,name:x.name,slug:x.slug,locationType:x.location_type,status:x.status,city:x.city,region:x.region,countryCode:x.country_code,timezone:x.timezone}));}
export async function listOrganizationServices(identity:Identity,organizationId:string){const {data,error}=await identity.client.from('organization_services').select('services(id,category_id,name,slug,description)').eq('organization_id',organizationId).eq('status','ACTIVE');unavailable(error);return (data??[]).flatMap((x:any)=>x.services?[serviceSchema.parse({id:x.services.id,categoryId:x.services.category_id,name:x.services.name,slug:x.services.slug,description:x.services.description})]:[]);}
const requestColumns='id,vehicle_id,organization_id,location_id,service_id,status,customer_note,service_location_text,city,region,postal_code,country_code,mobile_service_preference,preferred_start_at,preferred_end_at,urgency,assigned_mechanic_id,created_at,updated_at';
function serviceRequest(row:any){return serviceRequestSchema.parse({id:row.id,vehicleId:row.vehicle_id,organizationId:row.organization_id,locationId:row.location_id,serviceId:row.service_id,status:row.status,customerNote:row.customer_note,serviceLocationText:row.service_location_text,city:row.city,region:row.region,postalCode:row.postal_code,countryCode:row.country_code,mobileServicePreference:row.mobile_service_preference,preferredStartAt:row.preferred_start_at?iso(row.preferred_start_at):null,preferredEndAt:row.preferred_end_at?iso(row.preferred_end_at):null,urgency:row.urgency,assignedMechanicId:row.assigned_mechanic_id,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)});}
function mechanicSummary(row:any){const value=Array.isArray(row)?row[0]:row;return value?{id:value.id,slug:value.slug,publicName:value.public_name,headline:value.headline,verified:value.verification_status==='VERIFIED'}:undefined;}
function jobOffer(row:any){return jobOfferSchema.parse({id:row.id,serviceRequestId:row.service_request_id,status:row.status,offeredAt:iso(row.offered_at),expiresAt:iso(row.expires_at),respondedAt:row.responded_at?iso(row.responded_at):null,declineReason:row.decline_reason,mechanic:mechanicSummary(row.professional_profiles)});}
function assignment(row:any){return assignmentSchema.parse({id:row.id,serviceRequestId:row.service_request_id,jobOfferId:row.job_offer_id,mechanicId:row.mechanic_id,status:row.status,assignedAt:iso(row.assigned_at),activatedAt:row.activated_at?iso(row.activated_at):null,mechanic:mechanicSummary(row.professional_profiles)});}
export async function getServiceRequest(identity:Identity,id:string){const {data,error}=await identity.client.from('service_requests').select(requestColumns).eq('id',id).maybeSingle();unavailable(error);if(!data)throw new AppError('NOT_FOUND',404,'Service request was not found.');return serviceRequest(data);}
export async function listServiceRequests(identity:Identity,limit:number,offset:number){const {data,error}=await identity.client.from('service_requests').select(requestColumns).order('created_at',{ascending:false}).range(offset,offset+limit);unavailable(error);const rows=data??[];return {items:rows.slice(0,limit).map(serviceRequest),page:{limit,offset,hasMore:rows.length>limit}};}
export async function createServiceRequest(identity:Identity,input:any){const {data,error}=await identity.client.rpc('create_marketplace_service_request',{p_vehicle_id:input.vehicleId,p_service_id:input.serviceId,p_customer_note:input.customerNote??null,p_organization_id:input.organizationId??null,p_location_id:input.locationId??null,p_service_location_text:input.serviceLocationText??null,p_city:input.city??null,p_region:input.region??null,p_postal_code:input.postalCode??null,p_country_code:input.countryCode,p_latitude:input.latitude??null,p_longitude:input.longitude??null,p_mobile_service_preference:input.mobileServicePreference,p_preferred_start_at:input.preferredStartAt??null,p_preferred_end_at:input.preferredEndAt??null,p_urgency:input.urgency,p_submit:input.submit,p_idempotency_key:input.idempotencyKey});if(error||!data)throw new AppError('FORBIDDEN',403,'Service request is not permitted.');return getServiceRequest(identity,data);}
export async function cancelServiceRequest(identity:Identity,id:string,reason?:string){const {data,error}=await identity.client.rpc('cancel_service_request',{p_request_id:id,p_reason:reason??null});if(error||!data)throw new AppError('CONFLICT',409,'Service request cannot be cancelled.');return getServiceRequest(identity,data);}
export async function listRequestOffers(identity:Identity,requestId:string){await getServiceRequest(identity,requestId);const {data,error}=await identity.client.from('job_offers').select('id,service_request_id,status,offered_at,expires_at,responded_at,decline_reason,professional_profiles!job_offers_mechanic_id_fkey(id,slug,public_name,headline,verification_status)').eq('service_request_id',requestId).eq('status','ACCEPTED').order('responded_at');unavailable(error);return (data??[]).map(jobOffer);}
export async function listJobOpportunities(identity:Identity,limit:number,offset:number){const {data,error}=await identity.client.from('job_offers').select('id,service_request_id,status,offered_at,expires_at,responded_at,decline_reason').order('offered_at',{ascending:false}).range(offset,offset+limit);unavailable(error);const rows=data??[];return {items:rows.slice(0,limit).map(jobOffer),page:{limit,offset,hasMore:rows.length>limit}};}
export async function getJobOffer(identity:Identity,id:string){const {data,error}=await identity.client.from('job_offers').select('id,service_request_id,status,offered_at,expires_at,responded_at,decline_reason').eq('id',id).maybeSingle();unavailable(error);if(!data)throw new AppError('NOT_FOUND',404,'Job offer was not found.');return jobOffer(data);}
export async function respondJobOffer(identity:Identity,id:string,input:{accept:boolean;declineReason?:string}){const {error}=await identity.client.rpc('respond_to_job_offer',{p_offer_id:id,p_accept:input.accept,p_decline_reason:input.declineReason??null});if(error)throw new AppError('CONFLICT',409,'Job offer can no longer be changed.');return getJobOffer(identity,id);}
export async function confirmJobOffer(identity:Identity,id:string){const {data,error}=await identity.client.rpc('confirm_job_offer',{p_offer_id:id});if(error||!data)throw new AppError('CONFLICT',409,'Job offer cannot be confirmed.');const result=await identity.client.from('service_request_assignments').select('id,service_request_id,job_offer_id,mechanic_id,status,assigned_at,activated_at,professional_profiles!service_request_assignments_mechanic_id_fkey(id,slug,public_name,headline,verification_status)').eq('id',data).single();unavailable(result.error);return assignment(result.data);}
export async function listAssignedJobs(identity:Identity){const {data,error}=await identity.client.from('service_request_assignments').select('id,service_request_id,job_offer_id,mechanic_id,status,assigned_at,activated_at').order('assigned_at',{ascending:false});unavailable(error);return (data??[]).map(assignment);}

function page(total:number,limit:number,offset:number){return {limit,offset,total,hasMore:offset+limit<total};}
function mechanic(row:any){return publicMechanicSchema.parse({id:row.id,slug:row.slug,publicName:row.public_name,headline:row.headline,biography:row.biography,verified:row.verified,operationMode:row.operation_mode,mobileCapable:row.mobile_capable,services:row.services??[],vehicleMakes:row.vehicle_makes??[],specialties:row.specialties??[],serviceAreas:row.service_areas??[],shops:row.shops??[]});}
function shop(row:any){return publicShopSchema.parse({id:row.id,slug:row.slug,name:row.name,description:row.description,organizationType:row.organization_type,verified:row.verified,websiteUrl:row.website_url,publicPhone:row.public_phone,locations:row.locations??[],services:row.services??[],vehicleMakes:row.vehicle_makes??[],mechanics:row.mechanics??[]});}
export async function searchMechanics(config:WorkerConfig,input:z.infer<typeof mechanicSearchInputSchema>){const {data,error}=await publicClient(config).rpc('search_public_mechanics',{p_query:input.query??null,p_city:input.city??null,p_region:input.region??null,p_postal_code:input.postalCode??null,p_latitude:input.latitude??null,p_longitude:input.longitude??null,p_radius_miles:input.radiusMiles??null,p_service_slug:input.service??null,p_vehicle_make_slug:input.vehicleMake??null,p_specialty_slug:input.specialty??null,p_mobile:input.mobile??null,p_verified:input.verified,p_limit:input.limit,p_offset:input.offset});unavailable(error);const rows=data??[];return mechanicSearchResultSchema.parse({items:rows.map(mechanic),page:page(Number(rows[0]?.total_count??0),input.limit,input.offset)});}
export async function searchShops(config:WorkerConfig,input:z.infer<typeof shopSearchInputSchema>){const {data,error}=await publicClient(config).rpc('search_public_shops',{p_query:input.query??null,p_city:input.city??null,p_region:input.region??null,p_postal_code:input.postalCode??null,p_service_slug:input.service??null,p_vehicle_make_slug:input.vehicleMake??null,p_verified:input.verified??null,p_limit:input.limit,p_offset:input.offset});unavailable(error);const rows=data??[];return shopSearchResultSchema.parse({items:rows.map(shop),page:page(Number(rows[0]?.total_count??0),input.limit,input.offset)});}
export async function getPublicMechanic(config:WorkerConfig,slug:string){const {data,error}=await publicClient(config).rpc('search_public_mechanics',{p_slug:slug,p_limit:1,p_offset:0});unavailable(error);if(!data?.[0])throw new AppError('NOT_FOUND',404,'Mechanic was not found.');return mechanic(data[0]);}
export async function getPublicShop(config:WorkerConfig,slug:string){const {data,error}=await publicClient(config).rpc('search_public_shops',{p_slug:slug,p_limit:1,p_offset:0});unavailable(error);if(!data?.[0])throw new AppError('NOT_FOUND',404,'Shop was not found.');return shop(data[0]);}
export async function searchPublicServices(config:WorkerConfig,input:z.infer<typeof serviceSearchInputSchema>){let query=publicClient(config).from('services').select('id,category_id,name,slug,description,service_categories!inner(name,slug)',{count:'exact'}).eq('status','ACTIVE');if(input.query)query=query.or(`name.ilike.%${input.query.replace(/[%_,()]/g,'')}%,description.ilike.%${input.query.replace(/[%_,()]/g,'')}%`);if(input.category)query=query.eq('service_categories.slug',input.category);const {data,error,count}=await query.order('name').range(input.offset,input.offset+input.limit-1);unavailable(error);return serviceSearchResultSchema.parse({items:(data??[]).map((row:any)=>publicServiceSchema.parse({id:row.id,categoryId:row.category_id,name:row.name,slug:row.slug,description:row.description,categoryName:row.service_categories.name})),page:page(count??0,input.limit,input.offset)});}
