/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from '@supabase/supabase-js';
import { profileSchema,organizationRoleSchema,organizationSchema,vehicleSchema,ownershipSchema,vehicleMakeSchema,vehicleModelSchema,serviceCategorySchema,serviceSchema,locationSchema,serviceRequestSchema } from '@cnmechanic/schemas';
import type { IdentityRepository } from '@cnmechanic/domain';
import type { WorkerConfig } from '@cnmechanic/config';
import type { Identity } from './auth';
import { AppError } from './errors';
export function identityRepository(identity:Identity):IdentityRepository{
 async function profile(displayName?:string){
  const query=displayName===undefined?identity.client.from('profiles').select('id,display_name,created_at').eq('id',identity.userId):identity.client.from('profiles').update({display_name:displayName}).eq('id',identity.userId).select('id,display_name,created_at');
  const {data,error}=await query.single();if(error || !data)throw new AppError('SERVICE_UNAVAILABLE',503,'Profile is unavailable.');
  return profileSchema.parse({id:data.id,displayName:data.display_name,createdAt:new Date(data.created_at as string).toISOString()});
 }
 return {getProfile:()=>profile(),updateProfile:profile};
}
export async function getOrganization(identity:Identity,id:string){
 const {data:members,error:memberError}=await identity.client.from('organization_memberships').select('role').eq('organization_id',id).eq('user_id',identity.userId).eq('active',true);
 if(memberError)throw new AppError('SERVICE_UNAVAILABLE',503,'Membership service is unavailable.');
 const roles=organizationRoleSchema.array().parse((members??[]).map(m=>m.role));
 if(!roles.length)throw new AppError('FORBIDDEN',403,'Organization access is not permitted.');
 const {data,error}=await identity.client.from('organizations').select('id,name').eq('id',id).single();
 if(error || !data)throw new AppError('FORBIDDEN',403,'Organization access is not permitted.');
 return organizationSchema.parse({...data,roles});
}
const iso=(value:string)=>new Date(value).toISOString();
function vehicle(row:any){const model=row.vehicle_models;return vehicleSchema.parse({id:row.id,model:{id:model.id,makeId:model.make_id,name:model.name,slug:model.slug,startYear:model.start_year,endYear:model.end_year},modelYear:row.model_year,trim:row.trim,engineDescription:row.engine_description,propulsionType:row.propulsion_type,drivetrain:row.drivetrain,transmissionType:row.transmission_type,mileage:row.mileage,status:row.status,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)});}
function unavailable(error:unknown){if(error)throw new AppError('SERVICE_UNAVAILABLE',503,'Core domain data is unavailable.');}
export async function listVehicles(identity:Identity){const {data,error}=await identity.client.from('vehicles').select('id,model_year,trim,engine_description,propulsion_type,drivetrain,transmission_type,mileage,status,created_at,updated_at,vehicle_models(id,make_id,name,slug,start_year,end_year)').order('created_at',{ascending:false});unavailable(error);return (data??[]).map(vehicle);}
export async function getVehicle(identity:Identity,id:string){const {data,error}=await identity.client.from('vehicles').select('id,model_year,trim,engine_description,propulsion_type,drivetrain,transmission_type,mileage,status,created_at,updated_at,vehicle_models(id,make_id,name,slug,start_year,end_year)').eq('id',id).maybeSingle();unavailable(error);if(!data)throw new AppError('NOT_FOUND',404,'Vehicle was not found.');return vehicle(data);}
export async function createVehicle(identity:Identity,input:any){const {data,error}=await identity.client.rpc('create_vehicle_with_owner',{p_model_id:input.modelId,p_model_year:input.modelYear,p_trim:input.trim??null,p_engine_description:input.engineDescription??null,p_propulsion_type:input.propulsionType,p_drivetrain:input.drivetrain??null,p_transmission_type:input.transmissionType??null,p_mileage:input.mileage??null,p_vin:input.vin??null});if(error||!data)throw new AppError('CONFLICT',409,'Vehicle could not be created.');return getVehicle(identity,data);}
export async function listOwnerships(identity:Identity,id:string){const {data,error}=await identity.client.from('vehicle_ownerships').select('id,vehicle_id,ownership_status,ownership_started_at,ownership_ended_at,source_type').eq('vehicle_id',id).order('ownership_started_at',{ascending:false});unavailable(error);return (data??[]).map((row:any)=>ownershipSchema.parse({id:row.id,vehicleId:row.vehicle_id,ownershipStatus:row.ownership_status,ownershipStartedAt:iso(row.ownership_started_at),ownershipEndedAt:row.ownership_ended_at?iso(row.ownership_ended_at):null,sourceType:row.source_type}));}
function publicClient(config:WorkerConfig){if(!config.SUPABASE_URL||!config.SUPABASE_PUBLISHABLE_KEY)throw new AppError('SERVICE_UNAVAILABLE',503,'Catalog is unavailable.');return createClient(config.SUPABASE_URL,config.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});}
export async function listVehicleMakes(config:WorkerConfig){const {data,error}=await publicClient(config).from('vehicle_makes').select('id,name,slug').order('name');unavailable(error);return (data??[]).map((x:any)=>vehicleMakeSchema.parse(x));}
export async function listVehicleModels(config:WorkerConfig){const {data,error}=await publicClient(config).from('vehicle_models').select('id,make_id,name,slug,start_year,end_year').order('name');unavailable(error);return (data??[]).map((x:any)=>vehicleModelSchema.parse({id:x.id,makeId:x.make_id,name:x.name,slug:x.slug,startYear:x.start_year,endYear:x.end_year}));}
export async function listCategories(config:WorkerConfig){const {data,error}=await publicClient(config).from('service_categories').select('id,name,slug,description').order('name');unavailable(error);return (data??[]).map((x:any)=>serviceCategorySchema.parse(x));}
export async function listServices(config:WorkerConfig){const {data,error}=await publicClient(config).from('services').select('id,category_id,name,slug,description').order('name');unavailable(error);return (data??[]).map((x:any)=>serviceSchema.parse({id:x.id,categoryId:x.category_id,name:x.name,slug:x.slug,description:x.description}));}
export async function listLocations(identity:Identity,organizationId:string){const {data,error}=await identity.client.from('locations').select('id,organization_id,name,slug,location_type,status,city,region,country_code,timezone').eq('organization_id',organizationId);unavailable(error);return (data??[]).map((x:any)=>locationSchema.parse({id:x.id,organizationId:x.organization_id,name:x.name,slug:x.slug,locationType:x.location_type,status:x.status,city:x.city,region:x.region,countryCode:x.country_code,timezone:x.timezone}));}
export async function listOrganizationServices(identity:Identity,organizationId:string){const {data,error}=await identity.client.from('organization_services').select('services(id,category_id,name,slug,description)').eq('organization_id',organizationId).eq('status','ACTIVE');unavailable(error);return (data??[]).flatMap((x:any)=>x.services?[serviceSchema.parse({id:x.services.id,categoryId:x.services.category_id,name:x.services.name,slug:x.services.slug,description:x.services.description})]:[]);}
export async function createServiceRequest(identity:Identity,input:any){const {data,error}=await identity.client.from('service_requests').insert({customer_profile_id:identity.userId,vehicle_id:input.vehicleId,organization_id:input.organizationId,location_id:input.locationId??null,service_id:input.serviceId,customer_note:input.customerNote??null}).select('id,vehicle_id,organization_id,location_id,service_id,status,customer_note,created_at,updated_at').single();if(error||!data)throw new AppError('FORBIDDEN',403,'Service request is not permitted.');return serviceRequestSchema.parse({id:data.id,vehicleId:data.vehicle_id,organizationId:data.organization_id,locationId:data.location_id,serviceId:data.service_id,status:data.status,customerNote:data.customer_note,createdAt:iso(data.created_at),updatedAt:iso(data.updated_at)});}
