/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/worker/wrangler.jsonc --include-runtime=false apps/worker/src/worker-configuration.d.ts` (hash: 2a5f8725b1754ec8cbad39de78f5928b)
interface __BaseEnv_Env {
	ENVIRONMENT: "preview" | "production" | "local";
	ALLOWED_ORIGINS: "https://preview.cnmechanic.com" | "https://www.cnmechanic.com" | "http://127.0.0.1:5173,http://localhost:5173";
	SUPABASE_URL?: "https://fzvqeeydbblcaxjrfwxl.supabase.co";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface PreviewEnv {
		ENVIRONMENT: "preview";
		ALLOWED_ORIGINS: "https://preview.cnmechanic.com";
	}
	interface ProductionEnv {
		ENVIRONMENT: "production";
		ALLOWED_ORIGINS: "https://www.cnmechanic.com";
		SUPABASE_URL: "https://fzvqeeydbblcaxjrfwxl.supabase.co";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ALLOWED_ORIGINS" | "SUPABASE_URL">> {}
}
