import { describe,it,expect,vi } from 'vitest';
import { paginationSchema,profileUpdateSchema } from '@cnmechanic/schemas';
import { workerConfigSchema,webConfigSchema,canonicalUrl,structuredDataJson } from '@cnmechanic/config';
import { createApiClient } from '@cnmechanic/api-client';
import { platformRegistry,registerBrowserTools,ToolRegistry } from '@cnmechanic/webmcp';
const client=createApiClient({baseUrl:'https://api.invalid',fetch:async()=>Response.json({data:{name:'CNMechanic',version:'0.1.0',apiVersion:'v1',stage:'foundation'},requestId:crypto.randomUUID()})});
describe('contracts and configuration',()=>{
 it('bounds pagination and rejects extra write fields',()=>{expect(paginationSchema.parse({limit:'10'}).limit).toBe(10);expect(paginationSchema.safeParse({limit:1000}).success).toBe(false);expect(profileUpdateSchema.safeParse({displayName:'A',role:'SUPER_ADMIN'}).success).toBe(false);expect(profileUpdateSchema.safeParse({displayName:' '}).success).toBe(false);});
 it('rejects wildcard, insecure, credential-bearing, mixed auth and unsafe production environments',()=>{for(const input of [{ENVIRONMENT:'local',ALLOWED_ORIGINS:'*'},{ENVIRONMENT:'preview',ALLOWED_ORIGINS:'http://example.com'},{ENVIRONMENT:'local',ALLOWED_ORIGINS:'http://localhost:5173',SUPABASE_URL:'http://127.0.0.1:54321'},{ENVIRONMENT:'production',ALLOWED_ORIGINS:'https://evil.test'}])expect(workerConfigSchema.safeParse(input).success).toBe(false);expect(webConfigSchema.safeParse({VITE_ENVIRONMENT:'production',VITE_API_BASE_URL:'http://127.0.0.1:8787'}).success).toBe(false);expect(webConfigSchema.safeParse({VITE_SUPABASE_URL:'https://example.supabase.co',VITE_SUPABASE_PUBLISHABLE_KEY:'sb_secret_never_allowed'}).success).toBe(false);});
 it('accepts complete production config and prevents secret-role keys',()=>{const input={ENVIRONMENT:'production',ALLOWED_ORIGINS:'https://www.cnmechanic.com',SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_example'};expect(workerConfigSchema.safeParse(input).success).toBe(true);const key=`header.${btoa(JSON.stringify({role:'service_role'}))}.signature`;expect(workerConfigSchema.safeParse({...input,SUPABASE_PUBLISHABLE_KEY:key}).success).toBe(false);});
 it('creates canonical URLs without tracking and escapes structured JSON',()=>{expect(canonicalUrl('/auth?token=secret#fragment')).toBe('https://www.cnmechanic.com/auth');expect(()=>canonicalUrl('//evil.test')).toThrow();expect(structuredDataJson({name:'</script>'})).not.toContain('<');});
});
describe('isolated WebMCP adapter',()=>{
 it('executes a public tool through the API and validates input',async()=>{const registry=platformRegistry(client);expect(await registry.execute('get_platform_info',{})).toMatchObject({stage:'foundation'});await expect(registry.execute('get_platform_info',{userId:'forged'})).rejects.toThrow();await expect(registry.execute('unknown',{})).rejects.toThrow();});
 it('rejects duplicate and sensitive tool registrations',()=>{const registry=platformRegistry(client),tool=registry.list()[0];expect(()=>registry.register(tool)).toThrow();expect(()=>new ToolRegistry().register({...tool,metadata:{...tool.metadata,risk:'FINANCIAL_CONFIRMATION_REQUIRED'}})).toThrow();});
 it('tolerates unsupported, throwing getters and rejected registration',async()=>{const registry=platformRegistry(client),signal=new AbortController().signal;expect(await registerBrowserTools(registry,{},signal)).toBe('unsupported');expect(await registerBrowserTools(registry,{get modelContext(){throw new Error('blocked');}},signal)).toBe('failed');expect(await registerBrowserTools(registry,{modelContext:{registerTool:()=>Promise.reject(new Error('unsupported'))}},signal)).toBe('failed');});
 it('registers correct schema and aborts on lifecycle teardown',async()=>{const registerTool=vi.fn();const controller=new AbortController();expect(await registerBrowserTools(platformRegistry(client),{modelContext:{registerTool}},controller.signal)).toBe('registered');const [tool,options]=registerTool.mock.calls[0];expect(tool.name).toBe('get_platform_info');expect(tool.inputSchema.additionalProperties).toBe(false);expect(tool.annotations.readOnlyHint).toBe(true);expect(await tool.execute({})).toMatchObject({name:'CNMechanic'});controller.abort();expect(options.signal.aborted).toBe(true);});
 it('cancels execution before API work',async()=>{const controller=new AbortController();controller.abort();await expect(platformRegistry(client).execute('get_platform_info',{},controller.signal)).rejects.toThrow('Cancelled');});
});
