import {describe,it,expect} from 'vitest';
import {applyProviderMetadata,applyRouteMetadata,resolveRouteMetadata} from '../apps/web/src/metadata';
type Kind='meta'|'link'|'script';
class FakeElement {name='';rel='';content='';href='';id='';type='';text='';dataset:Record<string,string>={};constructor(readonly kind:Kind,private readonly removeSelf:()=>void){}remove(){this.removeSelf();}}
class FakeDocument {title='';elements:FakeElement[]=[];head={append:(element:FakeElement)=>{this.elements.push(element);}};createElement(kind:Kind){const element=new FakeElement(kind,()=>{this.elements=this.elements.filter(value=>value!==element);});return element;}querySelector(selector:string){if(selector==='link[rel="canonical"]')return this.elements.find(element=>element.rel==='canonical')??null;if(selector==='#cn-jsonld')return this.elements.find(element=>element.id==='cn-jsonld')??null;const name=selector.match(/^meta\[name="(.+)"\]$/)?.[1];return name?this.elements.find(element=>element.name===name)??null:null;}}
function edgeDocument(path:string,title:string,description:string){const document=new FakeDocument();document.title=title;const link=document.createElement('link');link.rel='canonical';link.href=`https://www.cnmechanic.com${path}`;document.head.append(link);const meta=document.createElement('meta');meta.name='description';meta.content=description;document.head.append(meta);const robots=document.createElement('meta');robots.name='robots';robots.content='index, follow';document.head.append(robots);const json=document.createElement('script');json.id='cn-jsonld';json.dataset.canonical=link.href;json.text='{"server":true}';document.head.append(json);return document;}
const get=(document:FakeDocument,selector:string)=>document.querySelector(selector) as FakeElement;
describe('Phase 3 metadata hydration',()=>{
 it.each([['/mechanics/alex-technician','Alex Technician | CNMechanic','European diagnostics'],['/shops/euro-garage','Euro Garage | CNMechanic','Independent repair shop']])('preserves edge title, description, canonical, robots and JSON-LD for %s',path=>{const title=path.startsWith('/mechanics')?'Alex Technician | CNMechanic':'Euro Garage | CNMechanic',description=path.startsWith('/mechanics')?'European diagnostics':'Independent repair shop',document=edgeDocument(path,title,description),json=get(document,'#cn-jsonld');applyRouteMetadata(document as unknown as Document,resolveRouteMetadata(path));expect(document.title).toBe(title);expect(get(document,'meta[name="description"]').content).toBe(description);expect(get(document,'link[rel="canonical"]').href).toBe(`https://www.cnmechanic.com${path}`);expect(get(document,'meta[name="robots"]').content).toBe('index, follow');expect(get(document,'#cn-jsonld')).toBe(json);expect(document.title).not.toBe('Page not found | CNMechanic');});
 it.each([['/services/diagnostics','Diagnostics specialists | CNMechanic'],['/brands/bmw','BMW mechanics | CNMechanic']])('sets canonical taxonomy metadata after hydration for %s',(path,title)=>{const document=edgeDocument('/','Wrong | CNMechanic','Wrong');applyRouteMetadata(document as unknown as Document,resolveRouteMetadata(path));expect(document.title).toBe(title);expect(get(document,'meta[name="description"]').content).not.toBe('Wrong');expect(get(document,'link[rel="canonical"]').href).toBe(`https://www.cnmechanic.com${path}`);expect(get(document,'meta[name="robots"]').content).toBe('index, follow');expect(get(document,'#cn-jsonld').text).toContain('schema.org');});
 it('updates a client-navigated provider from real loaded data',()=>{const document=edgeDocument('/mechanics','Find a mechanic | CNMechanic','Search');applyRouteMetadata(document as unknown as Document,resolveRouteMetadata('/mechanics/alex-technician'));applyProviderMetadata(document as unknown as Document,{kind:'mechanic',slug:'alex-technician',name:'Alex Technician',description:'European diagnostics',verified:true});expect(document.title).toBe('Alex Technician | CNMechanic');expect(get(document,'meta[name="description"]').content).toBe('European diagnostics');expect(get(document,'#cn-jsonld').text).toContain('CN Verified');});
 it.each(['/unknown','/services/not-real','/brands/not-real'])('marks a genuine unknown route noindex with a 404 title for %s',path=>{const document=edgeDocument('/','Old | CNMechanic','Old');applyRouteMetadata(document as unknown as Document,resolveRouteMetadata(path));expect(document.title).toBe('Page not found | CNMechanic');expect(get(document,'meta[name="robots"]').content).toBe('noindex, nofollow');expect(document.querySelector('#cn-jsonld')).toBeNull();});
});
