import {describe,it,expect,vi} from 'vitest';
import {CandidateGenerationService} from '@cnmechanic/domain';
import {createApiClient} from '@cnmechanic/api-client';
import {serviceRequestCreateSchema,jobOfferResponseSchema,contracts} from '@cnmechanic/schemas';

const id=(suffix:string)=>`90000000-0000-4000-8000-${suffix.padStart(12,'0')}`;
const base={active:true,publicVisibility:'PUBLISHED' as const,verificationStatus:'VERIFIED' as const,lifecycleStatus:'ELIGIBLE_FOR_JOBS' as const,verified:true,serviceMatch:true,vehicleMakeMatch:true,geographyMatch:true,mobileCapable:true,shopCapable:true,distanceMiles:4,relevance:100};

describe('Phase 4 marketplace contracts',()=>{
 it('filters eligibility before ranking and bounds candidate batches',()=>{const service=new CandidateGenerationService();const candidates=[{...base,id:id('2'),relevance:80},{...base,id:id('1'),verificationStatus:'UNDER_REVIEW' as const,relevance:1000},{...base,id:id('3'),serviceMatch:false,relevance:2000},{...base,id:id('4'),distanceMiles:2,relevance:80}];expect(service.generate(candidates,'MOBILE',2).map(x=>x.id)).toEqual([id('4'),id('2')]);});
 it('honors mobile and shop compatibility',()=>{const service=new CandidateGenerationService();expect(service.generate([{...base,id:id('1'),mobileCapable:false}],'MOBILE')).toEqual([]);expect(service.generate([{...base,id:id('2'),shopCapable:false}],'SHOP')).toEqual([]);});
 it('requires ownership-safe request inputs and idempotency',()=>{expect(serviceRequestCreateSchema.safeParse({vehicleId:id('1'),serviceId:id('2'),countryCode:'US',idempotencyKey:'request-123'}).success).toBe(true);expect(serviceRequestCreateSchema.safeParse({vehicleId:id('1'),serviceId:id('2'),latitude:1,countryCode:'US',idempotencyKey:'short'}).success).toBe(false);});
 it('requires a reason for mechanic declines',()=>{expect(jobOfferResponseSchema.safeParse({accept:true}).success).toBe(true);expect(jobOfferResponseSchema.safeParse({accept:false}).success).toBe(false);expect(jobOfferResponseSchema.safeParse({accept:false,declineReason:'Not available'}).success).toBe(true);});
 it('uses canonical authenticated API routes for customer and mechanic actions',async()=>{const calls:string[]=[];const transport=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{calls.push(`${init?.method??'GET'} ${String(input)}`);const url=String(input);if(url.includes('/job-opportunities'))return Response.json({data:{items:[],page:{limit:20,offset:0,hasMore:false}},requestId:id('10')});if(url.includes('/service-requests'))return Response.json({data:{items:[],page:{limit:20,offset:0,hasMore:false}},requestId:id('10')});return Response.json({data:[],requestId:id('10')});});const client=createApiClient({baseUrl:'https://api.example',getToken:async()=>'token',fetch:transport});await client.serviceRequests();await client.jobOpportunities();await client.assignedJobs();expect(calls).toEqual(expect.arrayContaining(['GET https://api.example/api/v1/service-requests','GET https://api.example/api/v1/mechanic/job-opportunities','GET https://api.example/api/v1/mechanic/jobs']));expect(new Headers(transport.mock.calls[0][1]?.headers).get('authorization')).toBe('Bearer token');});
 it('publishes no Phase 4 action through WebMCP and documents every Worker contract',()=>{const transactional=Object.values(contracts).filter(contract=>contract.path.includes('service-requests')||contract.path.includes('job-offers')||contract.path.includes('/mechanic/'));expect(transactional.length).toBeGreaterThanOrEqual(8);expect(transactional.every(contract=>contract.auth)).toBe(true);});
});
