import {describe,it,expect,vi} from 'vitest';
import {ProviderEligibilityService,ProviderRankingService} from '@cnmechanic/domain';
import {createApiClient} from '@cnmechanic/api-client';
import {marketplaceRegistry} from '@cnmechanic/webmcp';
import {renderPublicProfile} from '../apps/web/pages-profile';
const requestId='90000000-0000-4000-8000-000000000001';
const empty={items:[],page:{limit:20,offset:0,total:0,hasMore:false}};
describe('Phase 3 marketplace architecture',()=>{
 it('keeps provider eligibility separate from ranking',()=>{const eligibility=new ProviderEligibilityService();expect(eligibility.isDiscoverable({active:true,publicVisibility:'PUBLISHED',verificationStatus:'VERIFIED',lifecycleStatus:'ACTIVE'})).toBe(true);expect(eligibility.isJobEligible({active:true,publicVisibility:'PUBLISHED',verificationStatus:'VERIFIED',lifecycleStatus:'ACTIVE'})).toBe(false);expect(eligibility.isDiscoverable({active:true,publicVisibility:'PUBLISHED',verificationStatus:'UNDER_REVIEW',lifecycleStatus:'ACTIVE'})).toBe(false);const ranked=new ProviderRankingService().rank([{id:'b',verified:true,relevance:1,distanceMiles:2},{id:'a',verified:false,relevance:100,distanceMiles:1}]);expect(ranked.map(x=>x.id)).toEqual(['b','a']);});
 it('serializes validated bounded filters in the shared API client',async()=>{const transport=vi.fn(async(input:RequestInfo|URL)=>{void input;return Response.json({data:empty,requestId});});const client=createApiClient({baseUrl:'https://api.example',fetch:transport});await client.searchMechanics({city:'Boston',limit:10});expect(String(transport.mock.calls[0][0])).toContain('/api/v1/search/mechanics?');expect(String(transport.mock.calls[0][0])).toContain('city=Boston');expect(()=>client.searchMechanics({limit:51})).toThrow();});
 it('exposes exactly five public READ_SAFE discovery tools',()=>{const client=createApiClient({baseUrl:'https://api.example',fetch:async()=>Response.json({data:empty,requestId})}),tools=marketplaceRegistry(client).list();expect(tools).toHaveLength(5);for(const tool of tools)expect(tool.metadata).toMatchObject({risk:'READ_SAFE',classification:'READ',authentication:'PUBLIC',confirmationRequired:false,auditRequired:true});expect(tools.map(tool=>tool.metadata.name)).toEqual(['search_mechanics','search_shops','get_mechanic_profile','get_shop_profile','search_services']);});
 it('renders canonical provider HTML and real 404s at the Pages edge',async()=>{const shell='<!doctype html><head><title>CNMechanic — The trusted mechanic network</title><link rel="canonical" href="https://www.cnmechanic.com/"/><meta name="description" content="base"/><meta name="robots" content="index, follow"/></head><body></body>',notFound='<!doctype html><head><title>Page not found | CNMechanic</title><meta name="description" content="The requested CNMechanic page was not found."/><meta name="robots" content="noindex, nofollow"/></head><body></body>',assets={fetch:vi.fn(async(input:Request)=>new Response(new URL(input.url).pathname==='/404.html'?notFound:shell,{headers:{'x-test':'asset'}}))};const original=globalThis.fetch;globalThis.fetch=vi.fn(async()=>Response.json({data:{slug:'alex',publicName:'Alex & Co',headline:'Diagnostics',verified:true}}));try{const response=await renderPublicProfile({request:new Request('https://www.cnmechanic.com/mechanics/alex'),params:{slug:'alex'},env:{ASSETS:assets,VITE_API_BASE_URL:'https://api.cnmechanic.com'}},'mechanics');expect(response.status).toBe(200);const html=await response.text();expect(html).toContain('https://www.cnmechanic.com/mechanics/alex');expect(html).toContain('<title>Alex &amp; Co | CNMechanic</title>');expect(html).toContain('<meta name="description" content="Diagnostics"/>');expect(html).toContain('<meta name="robots" content="index, follow"/>');expect(html.match(/name="robots"/g)).toHaveLength(1);expect(html).toContain('id="cn-jsonld"');globalThis.fetch=vi.fn(async()=>new Response(null,{status:404}));const missing=await renderPublicProfile({request:new Request('https://www.cnmechanic.com/mechanics/missing'),params:{slug:'missing'},env:{ASSETS:assets}},'mechanics');expect(missing.status).toBe(404);const missingHtml=await missing.text();expect(missingHtml).toContain('<title>Page not found | CNMechanic</title>');expect(missingHtml).toContain('noindex, nofollow');}finally{globalThis.fetch=original;}});
});
