import { beforeEach,afterEach,describe,it,expect,vi } from 'vitest';
import worker from '../apps/worker/src/index';
import { createApiClient,ApiError } from '@cnmechanic/api-client';
import { healthSchema,versionSchema,envelope,profileSchema,contracts } from '@cnmechanic/schemas';
import { authorize } from '../apps/worker/src/authorization';
const env={ENVIRONMENT:'local',ALLOWED_ORIGINS:'http://127.0.0.1:5173',SUPABASE_URL:'http://127.0.0.1:54321',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test_fixture'} as unknown as Env;
const id='10000000-0000-4000-8000-000000000001';
function req(path:string,init?:RequestInit){return new Request(`http://127.0.0.1:8787${path}`,init);}
const auth={Authorization:'Bearer test-credential'};
beforeEach(()=>vi.spyOn(console,'log').mockImplementation(()=>{}));
afterEach(()=>vi.restoreAllMocks());
function backend(){return vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.endsWith('/auth/v1/user'))return Response.json({id,aud:'authenticated',role:'authenticated',email:'test@example.invalid',is_anonymous:false});if(url.includes('/rest/v1/profiles')){expect(new Headers(init?.headers).get('authorization')).toBe('Bearer test-credential');expect(url).toContain(`id=eq.${id}`);return Response.json({id,display_name:'Owner',created_at:'2026-09-19T12:00:00Z'});}return Response.json([]);});}
describe('Worker request pipeline',()=>{
 it('serves health and version with safe headers and valid contracts',async()=>{for(const [path,schema]of [['/api/v1/health',healthSchema],['/api/v1/version',versionSchema]] as const){const response=await worker.fetch(req(path),env);expect(response.status).toBe(200);expect(envelope(schema).safeParse(await response.json()).success).toBe(true);expect(response.headers.get('Cache-Control')).toBe('no-store');expect(response.headers.get('X-Request-ID')).toMatch(/^[a-f0-9-]{36}$/);}});
 it('rejects missing, malformed and remote-invalid credentials',async()=>{for(const Authorization of ['', 'Basic abc','Bearer a b']){expect((await worker.fetch(req('/api/v1/me',{headers:{Authorization}}),env)).status).toBe(401);}vi.spyOn(globalThis,'fetch').mockResolvedValue(Response.json({message:'invalid token'},{status:401}));expect((await worker.fetch(req('/api/v1/me',{headers:auth}),env)).status).toBe(401);});
 it('derives identity from Auth and propagates the user token to RLS',async()=>{backend();const response=await worker.fetch(req('/api/v1/me',{headers:{...auth,'X-User-ID':'attacker'}}),env);expect(response.status).toBe(200);expect(envelope(profileSchema).parse(await response.json()).data.id).toBe(id);});
 it('denies anonymous Supabase identities',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(Response.json({id,is_anonymous:true}));expect((await worker.fetch(req('/api/v1/me',{headers:auth}),env)).status).toBe(403);});
 it('rejects forged owner fields and invalid organization IDs',async()=>{backend();expect((await worker.fetch(req('/api/v1/me',{method:'PATCH',headers:{...auth,'Content-Type':'application/json'},body:JSON.stringify({displayName:'Owner',id:'attacker'})}),env)).status).toBe(400);expect((await worker.fetch(req('/api/v1/organizations/not-an-id',{headers:auth}),env)).status).toBe(400);});
 it('permits a valid profile edit through the domain service',async()=>{backend();const response=await worker.fetch(req('/api/v1/me',{method:'PATCH',headers:{...auth,'Content-Type':'application/json'},body:JSON.stringify({displayName:'Owner'})}),env);expect(response.status).toBe(200);});
 it('enforces streamed size limits, JSON and media type',async()=>{backend();for(const [body,type,status]of [['x'.repeat(4097),'application/json',413],['{','application/json',400],['{}','text/plain',415]] as const){const response=await worker.fetch(req('/api/v1/me',{method:'PATCH',headers:{...auth,'Content-Type':type},body}),env);expect(response.status).toBe(status);}});
 it('enforces exact origin and preflight allowlists',async()=>{const allowed=await worker.fetch(req('/api/v1/health',{headers:{Origin:'http://127.0.0.1:5173'}}),env);expect(allowed.headers.get('Access-Control-Allow-Origin')).toBe('http://127.0.0.1:5173');const denied=await worker.fetch(req('/api/v1/health',{headers:{Origin:'https://evil.test'}}),env);expect(denied.status).toBe(403);expect(denied.headers.has('Access-Control-Allow-Origin')).toBe(false);expect((await worker.fetch(req('/api/v1/me',{method:'OPTIONS',headers:{Origin:'http://127.0.0.1:5173','Access-Control-Request-Method':'PATCH','Access-Control-Request-Headers':'authorization,content-type'}}),env)).status).toBe(204);expect((await worker.fetch(req('/api/v1/me',{method:'OPTIONS',headers:{Origin:'http://127.0.0.1:5173','Access-Control-Request-Method':'DELETE'}}),env)).status).toBe(403);});
 it('allows browser preflight for authenticated POST routes',async()=>{
  const response=await worker.fetch(req('/api/v1/vehicles',{method:'OPTIONS',headers:{Origin:'http://127.0.0.1:5173','Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'authorization,content-type'}}),env);
  expect(response.status).toBe(204);
  expect(response.headers.get('Access-Control-Allow-Origin')).toBe('http://127.0.0.1:5173');
  expect(response.headers.get('Access-Control-Allow-Methods')).toContain('POST');
 });
 it('rejects unknown routes, unsupported methods and query fields',async()=>{expect((await worker.fetch(req('/mcp'),env)).status).toBe(404);expect((await worker.fetch(req('/api/v1/health',{method:'POST'}),env)).status).toBe(405);expect((await worker.fetch(req('/api/v1/health?secret=do-not-log'),env)).status).toBe(400);expect(JSON.stringify(vi.mocked(console.log).mock.calls)).not.toContain('do-not-log');});
 it('fails closed on malformed or incomplete hosted configuration',async()=>{const response=await worker.fetch(req('/api/v1/health'),{ENVIRONMENT:'production',ALLOWED_ORIGINS:'*',password:'never-leak'} as unknown as Env);expect(response.status).toBe(503);expect(JSON.stringify(await response.json())).not.toContain('never-leak');});
 it('returns no membership data to a nonmember',async()=>{backend();expect((await worker.fetch(req(`/api/v1/organizations/${id}`,{headers:auth}),env)).status).toBe(403);});
 it('has capability policies separate from authentication',()=>{expect(()=>authorize(['TECHNICIAN'],'organization:manage')).toThrow();expect(()=>authorize(['SHOP_OWNER'],'organization:manage')).not.toThrow();expect(()=>authorize([],'organization:read')).toThrow();});
 it('generates OpenAPI from the actual shared contracts',async()=>{const result=await worker.fetch(req('/openapi.json'),env);const spec=await result.json() as {paths:Record<string,unknown>};expect(Object.keys(spec.paths)).toEqual([...new Set(Object.values(contracts).map(c=>c.path))]);});
 it('typed client communicates with the Worker',async()=>{const client=createApiClient({baseUrl:'http://127.0.0.1:8787',fetch:(input,init)=>worker.fetch(new Request(input,init),env)});expect((await client.health()).status).toBe('ok');await expect(client.me()).rejects.toMatchObject({code:'AUTHENTICATION_REQUIRED',status:401});});
 it('typed client rejects invalid responses and times out',async()=>{const broken=createApiClient({baseUrl:'http://api.invalid',fetch:async()=>Response.json({data:{bad:true},requestId:crypto.randomUUID()})});await expect(broken.health()).rejects.toBeInstanceOf(ApiError);const slow=createApiClient({baseUrl:'http://api.invalid',timeoutMs:10,fetch:(_input,init)=>new Promise((_resolve,reject)=>{init?.signal?.addEventListener('abort',()=>reject(new Error('aborted')));})});await expect(slow.health()).rejects.toMatchObject({code:'REQUEST_ABORTED'});});
});
