import { useEffect,useState,type FormEvent } from 'react';
import { Link,NavLink,Route,Routes,useLocation } from 'react-router-dom';
import { canonicalUrl } from '@cnmechanic/config';
import { ApiError } from '@cnmechanic/api-client';
import type { Profile } from '@cnmechanic/schemas';
import { Button,Card,Input,Status } from './components';
import { useAuth } from './auth';
import { api,supabase } from './services';
function Metadata(){const location=useLocation();useEffect(()=>{const canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(canonical)canonical.href=canonicalUrl(location.pathname);document.title=location.pathname==='/'?'CNMechanic — The trusted mechanic network':`${location.pathname==='/account'?'Account':location.pathname==='/auth'?'Sign in':'Page not found'} | CNMechanic`;},[location.pathname]);return null;}
function Home(){const [status,setStatus]=useState('Not checked'),[busy,setBusy]=useState(false);async function check(){setBusy(true);try{const result=await api.health();setStatus(result.status==='ok'?'API connected':'API unavailable');}catch{setStatus('API unavailable. Please try again later.');}finally{setBusy(false);}}
 return <><div className="hero"><span className="badge">UNDER DEVELOPMENT</span><p className="eyebrow">PRECISION. TRANSPARENCY. TRUST.</p><h1>A better foundation<br/>for automotive care.</h1><p className="lead">We’re building CNMechanic, the trusted mechanic network. A place for vehicle owners and automotive professionals to connect with confidence.</p><p className="muted">The platform is in development. Service bookings are not available yet.</p><Link className="button" to="/auth">Account access <span aria-hidden="true">↗</span></Link></div><div className="foundation-grid"><Card><span className="eyebrow">01 / THE FOUNDATION</span><h2>Built on trust.</h2><p>Secure accounts and clear permissions come first. This release establishes the technical foundation for the network.</p></Card><Card><span className="eyebrow">02 / CONNECTION</span><h2>Platform connection</h2><p>Check the connection to the CNMechanic API.</p><Status>{status}</Status><Button className="secondary" disabled={busy} onClick={()=>void check()}>{busy?'Checking…':'Check connection'}</Button></Card></div></>;}
function AuthPage(){const {session,loading,error:sessionError}=useAuth();const [signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const form=e.currentTarget;const data=new FormData(form);const email=String(data.get('email')),password=String(data.get('password'));setBusy(true);setMessage('');setFailed(false);try{const result=signup?await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth`}}):await supabase.auth.signInWithPassword({email,password});if(result.error){setFailed(true);setMessage(signup?'Unable to create an account. Check your details and try again.':'Unable to sign in. Check your email and password.');}else{form.reset();setMessage(signup&&!result.data.session?'Check your email to confirm your account.':'You are signed in.');}}catch{setFailed(true);setMessage('Unable to reach the authentication service.');}finally{setBusy(false);}}
 if(loading)return <Status>Restoring session…</Status>;
 if(session)return <Card><h1>You’re signed in.</h1><Link className="button" to="/account">View account</Link></Card>;
 return <div className="narrow"><p className="eyebrow">CNMECHANIC ACCOUNT</p><h1>{signup?'Create an account':'Welcome back.'}</h1><p>Account access for the CNMechanic development platform.</p>{sessionError?<Status error>{sessionError}</Status>:null}{!supabase?<Status>Account access is not configured in this environment.</Status>:<form onSubmit={e=>void submit(e)}><Input id="email" label="Email address" name="email" type="email" autoComplete="email" required maxLength={254}/><Input id="password" label="Password" name="password" type="password" autoComplete={signup?'new-password':'current-password'} minLength={signup?12:1} maxLength={128} required/>{signup?<p className="muted">Use at least 12 characters.</p>:null}<Button disabled={busy} type="submit">{busy?'Please wait…':signup?'Create account':'Sign in'}</Button></form>}{message?<Status error={failed}>{message}</Status>:null}<Button className="text-button" disabled={busy} onClick={()=>{setSignup(!signup);setMessage('');}}>{signup?'Already have an account? Sign in':'New to CNMechanic? Create an account'}</Button></div>;
}
function Account(){const {session,loading}=useAuth();const [profile,setProfile]=useState<Profile|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;if(session)void api.me().then(p=>{if(live)setProfile(p);}).catch(()=>{if(live)setError('Unable to load your profile.');});return ()=>{live=false;};},[session]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');try{const next=await api.updateMe({displayName:String(new FormData(e.currentTarget).get('displayName'))});setProfile(next);setMessage('Profile saved.');}catch(err){setError(err instanceof ApiError?err.message:'Unable to save your profile.');}finally{setBusy(false);}}
 async function signOut(){setBusy(true);setError('');try{const result=await supabase?.auth.signOut();if(result?.error)setError('Unable to sign out. Please try again.');}catch{setError('Unable to sign out. Please try again.');}finally{setBusy(false);}}
 if(loading)return <Status>Restoring session…</Status>;
 if(!session)return <Card><h1>Sign in to your account.</h1><Link className="button" to="/auth">Sign in</Link></Card>;
 return <div className="narrow"><p className="eyebrow">YOUR ACCOUNT</p><h1>Account foundation</h1><p>Manage your profile. Marketplace features are still in development.</p>{profile?<form onSubmit={e=>void save(e)}><Input id="displayName" label="Display name" name="displayName" defaultValue={profile.displayName} maxLength={100} required/><Button disabled={busy}>Save profile</Button></form>:!error?<Status>Loading profile…</Status>:null}{error?<Status error>{error}</Status>:null}{message?<Status>{message}</Status>:null}<Button className="secondary" disabled={busy} onClick={()=>void signOut()}>Sign out</Button></div>;
}
export default function App(){const [menu,setMenu]=useState(false);const {session}=useAuth();return <><Metadata/><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="container nav"><Link className="brand" to="/" aria-label="CNMechanic home"><span>CN</span>MECHANIC<i aria-hidden="true"/></Link><button className="menu-button" aria-expanded={menu} aria-controls="primary-nav" onClick={()=>setMenu(!menu)}>Menu</button><nav id="primary-nav" aria-label="Primary" className={menu?'open':''}><NavLink to="/" onClick={()=>setMenu(false)}>Overview</NavLink><NavLink to={session?'/account':'/auth'} onClick={()=>setMenu(false)}>{session?'Account':'Sign in'} <span aria-hidden="true">↗</span></NavLink></nav></div></header><main id="main" className="container" tabIndex={-1}><Routes><Route path="/" element={<Home/>}/><Route path="/auth" element={<AuthPage/>}/><Route path="/account" element={<Account/>}/><Route path="*" element={<div className="narrow"><p className="eyebrow">404</p><h1>Page not found.</h1><p>This page doesn’t exist.</p><Link className="button" to="/">Return home</Link></div>}/></Routes></main><footer className="container footer"><span>CNMechanic</span><span>The trusted mechanic network. Under development.</span></footer></>;}
