import {canonicalUrl,structuredDataJson} from '@cnmechanic/config';
import {makeSlug,serviceTaxonomy,vehicleMakes} from './marketplace-content';
export interface PageMetadata {title:string;description:string;canonical?:string;robots:'index, follow'|'noindex, follow'|'noindex, nofollow';jsonLd?:Record<string,unknown>;}
export type RouteMetadata={mode:'set';metadata:PageMetadata}|{mode:'preserve-provider';canonical:string;robots:'index, follow'};
const staticPages:Record<string,{title:string;description:string;private?:boolean}>={
 '/':{title:'The trusted mechanic network',description:'Find trusted automotive specialists, organize your vehicle history, and move through every service with clarity.'},
 '/mechanics':{title:'Find a mechanic',description:'Search verified public CNMechanic mechanic profiles by service, vehicle make, expertise, and location.'},
 '/for-mechanics':{title:'Built for automotive professionals',description:'Join the trusted network built to help automotive professionals get discovered, build trust, and keep customers coming back.'},
 '/auth':{title:'Sign in',description:'Private CNMechanic account access.',private:true},'/account':{title:'Account',description:'Private CNMechanic account settings.',private:true},'/vehicles':{title:'Vehicles',description:'Private CNMechanic vehicle records.',private:true},
};
const notFound=():RouteMetadata=>({mode:'set',metadata:{title:'Page not found | CNMechanic',description:'The requested CNMechanic page was not found.',robots:'noindex, nofollow'}});
export function resolveRouteMetadata(pathname:string,hasQuery=false):RouteMetadata{
 const path=pathname==='/'?'/':pathname.replace(/\/+$/,'');
 const page=staticPages[path];if(page)return {mode:'set',metadata:{title:`${page.title} | CNMechanic`,description:page.description,canonical:canonicalUrl(path),robots:page.private?'noindex, nofollow':hasQuery?'noindex, follow':'index, follow'}};
 const mechanic=path.match(/^\/mechanics\/([a-z0-9]+(?:-[a-z0-9]+)*)$/),shop=path.match(/^\/shops\/([a-z0-9]+(?:-[a-z0-9]+)*)$/);
 if(mechanic||shop)return {mode:'preserve-provider',canonical:canonicalUrl(path),robots:'index, follow'};
 const service=path.match(/^\/services\/([a-z0-9]+(?:-[a-z0-9]+)*)$/);if(service){const item=serviceTaxonomy.find(([slug])=>slug===service[1]);if(!item)return notFound();const [,name,description]=item;return {mode:'set',metadata:{title:`${name} specialists | CNMechanic`,description,canonical:canonicalUrl(path),robots:'index, follow',jsonLd:{'@context':'https://schema.org','@type':'Service',name,description,provider:{'@type':'Organization',name:'CNMechanic',url:canonicalUrl('/')}}}};}
 const brand=path.match(/^\/brands\/([a-z0-9]+(?:-[a-z0-9]+)*)$/);if(brand){const name=vehicleMakes.find(value=>makeSlug(value)===brand[1]);if(!name)return notFound();const description=`Find verified public professionals who declare and document experience servicing ${name} vehicles.`;return {mode:'set',metadata:{title:`${name} mechanics | CNMechanic`,description,canonical:canonicalUrl(path),robots:'index, follow',jsonLd:{'@context':'https://schema.org','@type':'WebPage',name:`${name} mechanics`,url:canonicalUrl(path),isPartOf:{'@type':'WebSite',name:'CNMechanic',url:canonicalUrl('/')}}}};}
 return notFound();
}
function meta(document:Document,name:string){let element=document.querySelector<HTMLMetaElement>(`meta[name="${name}"]`);if(!element){element=document.createElement('meta');element.name=name;document.head.append(element);}return element;}
function canonical(document:Document){let element=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!element){element=document.createElement('link');element.rel='canonical';document.head.append(element);}return element;}
function removeJsonLd(document:Document){document.querySelector<HTMLScriptElement>('#cn-jsonld')?.remove();}
export function applyRouteMetadata(document:Document,route:RouteMetadata){if(route.mode==='preserve-provider')canonical(document).href=route.canonical;else if(route.metadata.canonical)canonical(document).href=route.metadata.canonical;else document.querySelector<HTMLLinkElement>('link[rel="canonical"]')?.remove();meta(document,'robots').content=route.mode==='set'?route.metadata.robots:route.robots;if(route.mode==='preserve-provider'){const script=document.querySelector<HTMLScriptElement>('#cn-jsonld');if(script?.dataset.canonical!==route.canonical)script?.remove();return;}document.title=route.metadata.title;meta(document,'description').content=route.metadata.description;removeJsonLd(document);if(route.metadata.jsonLd&&route.metadata.canonical){const script=document.createElement('script');script.id='cn-jsonld';script.type='application/ld+json';script.dataset.canonical=route.metadata.canonical;script.text=structuredDataJson(route.metadata.jsonLd);document.head.append(script);}}
export function applyProviderMetadata(document:Document,input:{kind:'mechanic'|'shop';slug:string;name:string;description:string;verified:boolean}){const canonicalValue=canonicalUrl(`/${input.kind==='mechanic'?'mechanics':'shops'}/${input.slug}`),jsonLd={'@context':'https://schema.org','@type':input.kind==='mechanic'?'Person':'AutoRepair',name:input.name,description:input.description,url:canonicalValue,...(input.verified?{award:'CN Verified'}:{})};applyRouteMetadata(document,{mode:'set',metadata:{title:`${input.name} | CNMechanic`,description:input.description,canonical:canonicalValue,robots:'index, follow',jsonLd}});}
