import { readFileSync,writeFileSync,mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadEnv } from 'vite';
import { canonicalOrigin,webConfigSchema,structuredDataJson } from '@cnmechanic/config';
const root=process.cwd(),dist=resolve(root,'dist');
const env=webConfigSchema.parse({...loadEnv('production',root,'VITE_'),...Object.fromEntries(Object.entries(process.env).filter(([k])=>k.startsWith('VITE_')))});
const index=readFileSync(resolve(dist,'index.html'),'utf8');
const services=[['diagnostics','Diagnostics','Find specialists who diagnose faults before replacing parts.'],['maintenance','Maintenance','Find professionals for scheduled and preventive vehicle care.'],['brakes','Brakes','Find professionals for brake inspection and repair.'],['electrical','Electrical','Find specialists for modern vehicle electrical systems.'],['inspection','Inspections','Find professionals for vehicle inspections.'],['tires','Tires & alignment','Find professionals for tire, alignment, and handling care.']] as const;
const makes=['BMW','Mercedes-Benz','Audi','Volkswagen','Volvo','Porsche','MINI','Land Rover','Jaguar'];
function page(route:string,title:string,description:string,jsonLd?:Record<string,unknown>,robots='index, follow'){
 let html=index.replace('<link rel="canonical" href="https://www.cnmechanic.com/"/>',`<link rel="canonical" href="${canonicalOrigin}/${route}"/>`).replace('<title>CNMechanic | The Trusted Mechanic Network</title>',`<title>${title} | CNMechanic</title>`).replace(/<meta name="description" content="[^"]*"\/>/,`<meta name="description" content="${description}"/><meta name="robots" content="${robots}"/>`);
 if(jsonLd)html=html.replace('</head>',`<script type="application/ld+json">${structuredDataJson(jsonLd)}</script></head>`);
 mkdirSync(resolve(dist,route),{recursive:true});writeFileSync(resolve(dist,route,'index.html'),html);
}
page('for-mechanics','Built for automotive professionals','A national marketplace foundation for certified mechanics and repair businesses.');
for(const route of ['auth','account','vehicles'])page(route,route==='auth'?'Sign in':route[0].toUpperCase()+route.slice(1),'Private CNMechanic account area.',undefined,'noindex, nofollow');
page('mechanics','Find a mechanic','Search verified public CNMechanic mechanic profiles by service, vehicle make, expertise, and location.',{'@context':'https://schema.org','@type':'WebSite',name:'CNMechanic',url:`${canonicalOrigin}/mechanics`,potentialAction:{'@type':'SearchAction',target:`${canonicalOrigin}/mechanics?query={search_term_string}`,'query-input':'required name=search_term_string'}});
for(const [slug,name,description] of services)page(`services/${slug}`,`${name} specialists`,description,{'@context':'https://schema.org','@type':'Service',name,description,provider:{'@type':'Organization',name:'CNMechanic',url:canonicalOrigin}});
for(const name of makes){const slug=name.toLowerCase().replaceAll(' ','-');page(`brands/${slug}`,`${name} mechanics`,`Find verified public professionals who declare and document experience servicing ${name} vehicles.`,{'@context':'https://schema.org','@type':'WebPage',name:`${name} mechanics`,url:`${canonicalOrigin}/brands/${slug}`,isPartOf:{'@type':'WebSite',name:'CNMechanic',url:canonicalOrigin}});}
writeFileSync(resolve(dist,'404.html'),index.replace('<title>CNMechanic | The Trusted Mechanic Network</title>','<title>Page not found | CNMechanic</title>').replace('</head>','<meta name="robots" content="noindex, nofollow"/></head>'));
writeFileSync(resolve(dist,'robots.txt'),'User-agent: *\nAllow: /\nDisallow: /account\nDisallow: /auth\nDisallow: /vehicles\nSitemap: https://www.cnmechanic.com/sitemap.xml\n');
const urls=['','for-mechanics',...services.map(([slug])=>`services/${slug}`),...makes.map(name=>`brands/${name.toLowerCase().replaceAll(' ','-')}`)];
writeFileSync(resolve(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(path=>`<url><loc>${canonicalOrigin}/${path}</loc></url>`).join('')}</urlset>\n`);
writeFileSync(resolve(dist,'llms.txt'),'# CNMechanic\n\nCNMechanic connects customers who need a vehicle fixed with certified mechanics who receive qualified repair opportunities. Public discovery uses verified marketplace records; booking, dispatch, payments, availability changes, claims, and administration are not exposed to browser agents.\n\n- Mechanic search: /mechanics\n- Professional network: /for-mechanics\n- OpenAPI: https://api.cnmechanic.com/openapi.json\n- WebMCP tools: search_mechanics, search_shops, get_mechanic_profile, get_shop_profile, search_services (public READ_SAFE tools when browser support is available).\n');
const connect=[env.VITE_API_BASE_URL,env.VITE_SUPABASE_URL].filter(Boolean).join(' ');
writeFileSync(resolve(dist,'_headers'),`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Strict-Transport-Security: max-age=31536000; includeSubDomains\n  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self' ${connect}; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'\n/account*\n  X-Robots-Tag: noindex, nofollow\n/auth*\n  X-Robots-Tag: noindex, nofollow\n/vehicles*\n  X-Robots-Tag: noindex, nofollow\n`);
